$(document).ready(function(){
	$('.header__slider').slick({
		arrows:false,
		dots:true,
		adaptiveHeight:true,
		responsive:[
			{
				breakpoint:768,
				settings:{
					adaptiveHeight:false
				}
			}
		]
	});
});